config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: :destroy
  post "search/results", to: "cocktails#search"
  get "search/results", to: "cocktails#search"
  root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
require 'open-uri'
require 'json'

class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    url = "https://api.unsplash.com/search/photos?query=#{@cocktail.name}+cocktail+drink&orientation=landscape&client_id=5fe258ea2bd9e5e5444ddbbc3a8bb538be5d7b41a518e87cf394221cd9b236ba"
    doc = open(url).read
    json = JSON.parse(doc)
    @cocktail.name = @cocktail.name.capitalize
    if @cocktail.save
      img_url = json["results"][0]["urls"]["raw"].split("?")[0]
      @cocktail.img_url = img_url
      @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render "new"
    end
  end

  def search

    @cocktails_raw = Cocktail.all
    @query = params["query"]
    @cocktails = []
    unless @query.nil?
      @cocktails_raw.each do |cocktail|
        cocktail.doses.each do |dose|
          ingredient = Ingredient.find(dose.ingredient_id)
          @cocktails << cocktail if ingredient.name.downcase.include?(@query.downcase) && !@cocktails.include?(cocktail)
        end
      end
    end

  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create

    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    end
  end
  def destroy

    @dose = Dose.find(params[:id])
    @cocktail = Cocktail.find(@dose.cocktail_id)
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner home" style="background:url('https://images.unsplash.com/photo-1509807995916-c332365e2d9e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=4c8d364e633e2015fbac047f327ce098&auto=format&fit=crop&w=1942&q=80')">
  <div class="banner-body">
    <h1>Myster Cocktail</h1>
    <h3><%= link_to "Create a cocktail", new_cocktail_path%></h2>

  </div>

</div>
<div class="container">
  <div class="index-header">
    <div class="index-header-left">
      <h2>All available cocktails</h2>
    </div>
    <div class="index-header-right">
      <form action=<%= search_results_path %> method="post" class="search">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="text" name="query" placeholder="Search for ingredients" class="search-input">
        <input type="submit" class="search-blue" value="Search">
      </form>
    </div>
  </div>


  <% @cocktails.each do |cocktail| %>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="card">
      <% if cocktail.photo.present? %>
        <% path = cl_image_path cocktail.photo, height: 300, width: 300 %>
      <% elsif cocktail[:photo_url].present? %>
        <% path =  cl_image_path cocktail[:photo_url], height: 300, width: 300 %>
      <% else %>
        <% path = cocktail.img_url %>
      <% end %>
      <div class="card-body" style=<%="background:linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.1)),url(#{path})" %> >
        <h1><%= cocktail.name %></h1>
      </div>
      <div class="card-footer">
        <ul>
          <% cocktail.doses.first(4).each do |dose|   %>
            <% ingredient_id = dose.ingredient_id %>
            <% @ingredient = Ingredient.find(ingredient_id) %>
            <li><%=  "#{@ingredient.name} :  #{dose.description}"%></li>
          <% end %>
        </ul>
      </div>
      <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
    </div>

  </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="wrapper">

<div class="col-xs-6 col-xs-offset-3">
  <h1 class="text-center">Create a new cocktail</h1>
  <%=  simple_form_for @cocktail do |f|%>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Add recipe", class: "btn btn-primary centered-button"%>

  <% end %>
</div>
</div>

<!--  -->

app/views/cocktails/search.html.erb
<div class="container">
  <% if @cocktails.empty? %>
    <h2 class="text-center">No results</h2>
  <% else %>
    <% if @query == "" %>
      <h3 class="header">All available cocktails</h3>
    <% else %>
      <h3 class="header">All cocktails with <%= @query.capitalize %></h3>
    <% end %>
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="card">
        <% if cocktail.photo.present? %>
          <% path = cl_image_path cocktail.photo, height: 300, width: 300 %>
        <% else %>
          <% path = cocktail.img_url %>
        <% end %>
        <div class="card-body" style=<%="background:linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.1)),url(#{path})" %> >
          <h1><%= cocktail.name %></h1>
        </div>
        <div class="card-footer">
          <ul>
            <% cocktail.doses.each do |dose|   %>
              <% ingredient_id = dose.ingredient_id %>
              <% @ingredient = Ingredient.find(ingredient_id) %>
              <li><%=  "#{@ingredient.name} :  #{dose.description}"%></li>
            <% end %>
          </ul>


        </div>
        <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
      </div>

    </div>
    <% end %>
  <% end %>

</div>

app/views/cocktails/show.html.erb
<div class="wrapper">
<div class="col-xs-10 col-xs-offset-1">
  <div class="cocktail-details">
    <% if @cocktail.photo.present? %>
      <% path = cl_image_path @cocktail.photo, height: 300, width: 300 %>
    <% elsif @cocktail[:photo_url].present? %>
      <% path =  cl_image_path @cocktail[:photo_url], height: 300, width: 300 %>
    <% else %>
      <% path = @cocktail.img_url %>
    <% end %>
    <div class="cocktail-card" style=<%= "background:linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.1)),url(#{path})" %>>
      <h1><%= @cocktail.name %></h1>
    </div>
    <div class="ingredients-card">
      <div class="dose-link-card">
        <h3>Add a dose</h3>
        <div class="dose-link modal-link"></div>
      </div>
      <div class="recipe">
        <% @cocktail.doses.each do |dose| %>
          <% ingredient_id = dose.ingredient_id %>
          <% @ingredient = Ingredient.find(ingredient_id) %>
          <div class="dose">
            <div class="dose-description">
              <h3><%= @ingredient.name %></h3>
              <p><strong> <%= dose.description %></strong></p>
            </div>
            <%= link_to "Delete this dose", dose_path(dose), method: :delete %>
          </div>



        <% end %>
        <h3>Instructions</h3>
        <p><%= @cocktail.instruction %></p>
      </div>

    </div>

  </div>
</div>
</div>
<div class="add-dose-form">

  <div class="col-xs-6 col-xs-offset-3">
    <div>
      <h1>Add a dose to the <%= @cocktail.name %></h1>
      <%= simple_form_for [@cocktail, Dose.new] do |f| %>
        <%= f.association :ingredient, prompt: "Choose an ingredient" %>
        <%= f.input :description, placeholder: "4cl, half a lime, ..." %>
        <div class="text-center">
          <%= f.submit "Add", class: "btn btn-primary button-dose"%>
          <%= link_to "Cancel", cocktail_path(@cocktail), class: "btn btn-danger button-dose" %>
        </div>

      <% end %>
    </div>

  </div>


</div>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<div class="col-xs-4 col-xs-offset-4">

  <h1>Add a dose to the <%= @cocktail.name %></h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient, prompt: "Choose an ingredient" %>
    <%= f.input :description, placeholder: "4cl, half a lime, ..." %>
    <%= f.submit "Add", class: "btn btn-primary"%>
    <%= link_to "Cancel", cocktail_path(@cocktail), class: "btn btn-danger" %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <link href="https://fonts.googleapis.com/css?family=Playball" rel="stylesheet">
  </head>

  <body>

  <div class="cocktail-nav">
    <div class="nav-left">
      <h1><%= link_to "Myster Cocktail", cocktails_path %></h1>
    </div>
    <div class="right-nav">
      <form action=<%= search_results_path %> method="post" class="search">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="text" name="query" placeholder="Search for ingredients" class="search-input">
        <input type="submit" class="search-button" value="Search">
      </form>
      <h2><%= link_to "Create a cocktail", new_cocktail_path%></h2>
    </div>
  </div>
  <div class="content-margin-bottom content">
    <%= yield %>
  </div>



    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>